    # Generated by Django 5.1.3 on 2024-11-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

        dependencies = [
            ('arduino', '0001_initial'),
        ]

        operations = [
            migrations.CreateModel(
                name='SensorData',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('distancia', models.FloatField()),
                    ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ],
            ),
            migrations.AlterField(
                model_name='cliente',
                name='foto',
                field=models.ImageField(blank=True, null=True, upload_to=''),
            ),
        ]
