# Generated by Django 5.1.3 on 2024-11-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0002_sensordata_alter_cliente_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
