# Generated by Django 5.1.3 on 2024-11-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0003_delete_sensordata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arduino',
            new_name='ESP32',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='arduino',
            new_name='esp32',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='arduino',
            new_name='esp32',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='arduino',
            new_name='esp32',
        ),
    ]
